name: API ETL Pipeline

on:
    push:
        branches:
            - main

jobs:
    read-from-api:
        runs-on: ubuntu-latest

        steps:
            - name: chekout-code
              uses: actions/checkout@v2

            - name: set python
              uses: actions/setup-python@v6
              with:
                python-version: '3.10'

            - name: install dependencies
              run: pip install -r requirements.txt

            - name: get data from api
#under github secrets and variable we hvae create one api_toek secrets that we read it here
              env:
                "API_TOKEN": ${{secrets.API_TOKEN}}
              run: python api.py